# Develop override settings

url: https://github.com/atsushi729/atsushi729.github.io.git

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded